### ISSUE TITLE
i can not run stream sample success

### ISSUE THREAD

**Issue by wangzhenxing** [microsoft/cognitive-services-speech-sdk-go#11]
(**admin edit: Image redacted**)
run speech_recognizer:RecognizeOnceFromWavFile success

(**admin edit: Image redacted**)
but run dialog_service_connector:ListenOnceFromStream fail

is there any thing to fix it?

**Comment by trrwilson** [comment]
Hello! Thanks for contacting us.

I removed the images from the post because they contained your subscription key--we wouldn't want anyone generating traffic against your subscription without your knowledge and consent. But before removing them, it unfortunately looks like the one with the output from `dialog_service_connector:ListenOnceFromStream` is cut off right after the `SessionStarted` but before any form of error output.

Could you please share some more detail about the failure you're seeing for us to look into? Also: if you can add the config property to emit a log file ([documented here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging) not specifically for go, but the same idea of setting `SPEECH-LogFilename` to a path applies), that log information would be very helpful in determining what you're encountering.

Thanks again!

**Comment by wangzhenxing** [comment]
ok i will try

**Comment by glecaros** [comment]
Closing as this thread has not seen activity in over a month. Please feel free to reopen it if more help is needed.
