### ISSUE TITLE
Compressed ulaw file is not recognising. 

### ISSUE THREAD

**Issue by svarunan** [microsoft/cognitive-services-speech-sdk-go#81]
HI Team, 
I've a specific use case where, I'm streaming ulaw G.711 PCMU (8000, 16 bit, mono) to UDP server and trying to feed it to sdk as a stream, But not able to get this recognised. 
Steps i tried:
1. Get a sample ulaw file and used `audio.GetCompressedFormat(audio.MULAW)` to work it via SKD (gstreamer installer) but not recognising.
2. Captured the raw pcmu data in pcap and tried option 1 and still no success.
I'm following [this](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams?tabs=windows%2Cdebian%2Cjava-android%2Cterminal&pivots=programming-language-go)

Files i tried 
[Audio-samples.zip](https://github.com/microsoft/cognitive-services-speech-sdk-go/files/9963962/Audio-samples.zip)

Any sample with mulaw file or raw pcmu file streaming example to this repo 'd definitely help speed up.

Currently we use MS STT as primary service for this, but (Writing PCMU audio to .wav file and stream .wav file to MS) it has additional latency.
But feeding the same UDP stream to Google stt is working fine without any issues. 
here just use same streaming with below options
`					Encoding:                   3,
					SampleRateHertz:            8000,
					AudioChannelCount:          1,`

**Comment by jhakulin** [comment]
@svarunan Thanks for the report. We will add support for direct streaming of ALAW and MULAW as done already for other languages like C#, https://learn.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.audio.audiostreamwaveformat?view=azure-dotnet
I am not sure what is the specific issue with the Gstreamer, but instead of investigating that we will prioritize the work for directly supporting ALAW/MULAW formats without Gstreamer. I will update here once it is done.

**Comment by jhakulin** [comment]
@svarunan I have submitted the PR for allowing to stream ALAW and MULAW encoded data directly to service. Let us know if there are issues.

**Comment by svarunan** [comment]
I've used a different approach earlier to convert by raw ulaw to transform to PCM, now `audio.GetWaveFormat(8000, 16, 1, audio.WaveMULAW)` works for me directly. Thanks

**Comment by jhakulin** [comment]
@svarunan I'm glad it helps!
